"""The kappa bounds are claimed to hold *by construction*. These check that empirically.

If any of these fail, the structural guarantee the whole approach rests on is not
actually being delivered by the parameterization.
"""
import numpy as np
import pytest
import torch

from ftnode.diagnostics import A_stats, skew_stats
from ftnode.latent import KappaBudget, build_clamp, build_unbounded, build_youla


def test_budget_derivation_matches_the_notebooks():
    b = KappaBudget(sigma_min=0.1, kappa_max=25.0, skew_frac=0.6, m=4)
    assert b.budget == pytest.approx(2.4)
    assert b.c_K == pytest.approx(1.44)
    assert b.c_P == pytest.approx(0.96)
    assert b.sigma_max == pytest.approx(2.5)
    assert b.l_bound == pytest.approx(0.30984, abs=1e-5)
    assert b.sigma_max / b.sigma_min == pytest.approx(b.kappa_max)


def test_beta_min_scales_with_c_K():
    b = KappaBudget()
    assert b.beta_min(0.0) == 0.0
    assert b.beta_min(0.5) == pytest.approx(0.5 * b.c_K)


@pytest.mark.parametrize("builder", ["clamp", "youla"])
def test_kappa_is_capped_over_the_latent_box(builder, model_cfg, budget, latent_box):
    torch.manual_seed(0)
    model = build_clamp(model_cfg, budget) if builder == "clamp" else build_youla(model_cfg, budget)
    _, _, kappa = A_stats(model.dynamics, latent_box)
    assert kappa.max() <= budget.kappa_max + 1e-4, f"kappa hit {kappa.max():.3f}"


@pytest.mark.parametrize("builder", ["clamp", "youla", "unbounded"])
def test_A_is_contracting_over_the_latent_box(builder, model_cfg, budget, latent_box):
    """`sym(A) <= -sigma_min I` holds for every variant, bounded skew or not."""
    torch.manual_seed(0)
    model = {
        "clamp": lambda: build_clamp(model_cfg, budget),
        "youla": lambda: build_youla(model_cfg, budget),
        "unbounded": lambda: build_unbounded(model_cfg),
    }[builder]()
    maxre, _, _ = A_stats(model.dynamics, latent_box)
    assert maxre.max() <= -budget.sigma_min + 1e-4


@pytest.mark.parametrize("builder", ["clamp", "youla"])
def test_skew_norm_is_capped(builder, model_cfg, budget, latent_box):
    torch.manual_seed(0)
    model = build_clamp(model_cfg, budget) if builder == "clamp" else build_youla(model_cfg, budget)
    knorm, _ = skew_stats(model.dynamics, latent_box)
    assert knorm.max() <= budget.c_K + 1e-4


def test_sigma_max_is_capped(model_cfg, budget, latent_box):
    torch.manual_seed(0)
    _, smax, _ = A_stats(build_clamp(model_cfg, budget).dynamics, latent_box)
    assert smax.max() <= budget.sigma_max + 1e-4


def test_youla_skew_has_paired_singular_values(model_cfg, budget):
    """The Youla bound is exact *because* K = Q Sigma Q^T has doubled singular values.

    That structure is what lets `||K||_2 = max beta_j` be read off without an SVD.
    """
    torch.manual_seed(0)
    dyn = build_youla(model_cfg, budget).dynamics
    z = (2 * torch.rand(64, budget.m) - 1) * 2.0
    A = dyn.A(z)
    K = 0.5 * (A - A.transpose(-1, -2))
    sv = torch.linalg.svdvals(K)
    assert torch.allclose(sv[:, 0], sv[:, 1], atol=1e-5)
    assert torch.allclose(sv[:, 2], sv[:, 3], atol=1e-5)


def test_unbounded_variant_really_is_unbounded(model_cfg, budget):
    """The baseline must not accidentally satisfy the cap, or the comparison is empty.

    Its skew part is generated by an unconstrained network, so a sufficiently
    large input drives ||K|| past c_K.
    """
    torch.manual_seed(0)
    dyn = build_unbounded(model_cfg).dynamics
    with torch.no_grad():
        for p in dyn.S_net.net[-1].parameters():
            p.add_(torch.randn_like(p) * 5.0)
    z = (2 * torch.rand(256, budget.m) - 1) * 2.0
    knorm, _ = skew_stats(dyn, z)
    assert knorm.max() > budget.c_K


def test_youla_rejects_odd_latent_dim(budget):
    from ftnode.latent import LatentFTNODEYoula

    with pytest.raises(ValueError, match="even latent dim"):
        LatentFTNODEYoula(l_bound=0.3, c_K=1.44, m=5)


def test_clamp_accepts_the_safe_clamp(model_cfg, budget, latent_box):
    """Swapping in the eigvalsh clamp must not weaken the cap."""
    from ftnode.latent import spectral_clamp_safe

    torch.manual_seed(0)
    model = build_clamp(model_cfg, budget, clamp_fn=spectral_clamp_safe)
    _, _, kappa = A_stats(model.dynamics, latent_box)
    assert kappa.max() <= budget.kappa_max + 1e-4
